spring.application.name=bitflow-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/bitflow_db
spring.datasource.username=bitflow
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# App Configuration
bitflow.app.jwtSecret=bitflowSecretKeyHereYouShouldChangeThisToSomethingMoreSecureForProduction
bitflow.app.jwtExpirationMs=86400000
